### ISSUE TITLE
插件加载报错：Expected URL scheme 'http' or 'https' but no scheme was found for

### ISSUE THREAD

**Issue by cdn0x12** [limbang/mirai-console-mcsm-plugin#2]
mcl版本：`2.1.0-71ec418`
mirai版本：`2.11`
插件版本：`1.0.9`，`1.0.8`均出现此问题
前置插件已安装

报错内容：
```
E/MCSManager API: java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
        at mirai-console-mcsm-plugin-1.0.8.mirai2.jar//top.limbang.mcsm.MCSM.onEnable(MCSM.kt:77)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:131)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:278)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:35)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:50)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:178)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:235)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:464)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:168)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:167)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:52)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:89)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:79)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:101)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:109)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:148)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:189)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)
        at org.itxtech.mcl.Loader.start(Loader.java:189)
        at org.itxtech.mcl.Loader.main(Loader.java:79)
Caused by: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no scheme was found for
        at mirai-console-mcsm-plugin-1.0.8.mirai2.jar[private]//okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1261)
        at mirai-console-mcsm-plugin-1.0.8.mirai2.jar[private]//okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1634)
        at mirai-console-mcsm-plugin-1.0.8.mirai2.jar[private]//okhttp3.HttpUrl.get(HttpUrl.kt)
        at mirai-console-mcsm-plugin-1.0.8.mirai2.jar[private]//retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:506)
        at mirai-console-mcsm-plugin-1.0.8.mirai2.jar//top.limbang.mcsm.RetrofitClient$instance$2.invoke(RetrofitClient.kt:48)
        at mirai-console-mcsm-plugin-1.0.8.mirai2.jar//top.limbang.mcsm.RetrofitClient$instance$2.invoke(RetrofitClient.kt:46)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at mirai-console-mcsm-plugin-1.0.8.mirai2.jar//top.limbang.mcsm.RetrofitClient.getInstance(RetrofitClient.kt:46)
        at mirai-console-mcsm-plugin-1.0.8.mirai2.jar//top.limbang.mcsm.RetrofitClient.getMCSManagerApi(RetrofitClient.kt:59)
        at mirai-console-mcsm-plugin-1.0.8.mirai2.jar//top.limbang.mcsm.MCSMCompositeCommand.<clinit>(MCSMCompositeCommand.kt:34)
        ... 26 more
```

**Comment by limbang** [comment]
没找到库。先吧库直接复制进去用用吧 路径 plugin-libraries/com/squareup/
[5.zip](https://github.com/limbang/mirai-console-mcsm-plugin/files/9542542/5.zip)

**Comment by cdn0x12** [comment]
您提到的这个库在我这是存在的，我复制重启之后仍然报了相同的错误orz
我的jdk版本是`17.0.4.1`（不知道这个有没有用）

Update: 我新开了一个纯净环境，重新安装了mcl和mirai，只加载这个插件，还是会报同样的错误。

**Comment by limbang** [comment]
不好意思我重新测试了，是 配置文件的问题 ,因为 ide 和机器人都有以前的配置文件没发现这个问题，我更新下版本

**Comment by cdn0x12** [comment]
好的，辛苦了！！
